version = 0.1

[default.deploy.parameters]
stack_name = "serverless-image-processing-app"
resolve_s3 = true
s3_prefix = "serverless-image-processing-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
